### PR TITLE
Skip expect_r_process_snapshot() tests when lacking asciicast

### PR DESCRIPTION
**Pull request by MichaelChirico**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Why not install asciicast, rather?

**Comment by MichaelChirico** [comment]
because it's a Suggests dependency

**Comment by gaborcsardi** [comment]
Yes, because it is a development dependency, but not an optional development dependency. Like testthat. There is no proper way to express that, unfortunately.

What is the point of running the tests if we are skipping them?

**Comment by MichaelChirico** [comment]
Sorry, still not quite following.

 - This type of thing is pretty common. It's why `skip_if_not_installed()` exists, AIUI. See also `vdiffr` which skips in many environments too. On CRAN and in CI, you'll almost always have your Suggests installed, so you can be confident they're being run.
 - `expect_r_process_snapshot()` is only used in one test file (test-errors.R). We could also add the `skip_if_not_installed()` call to the top level of test-errors.R, but I've seen elsewhere Hadley advocating against that in favor of only using skips within `test_that()` calls. So the change here minimizes the diff while accomplishing the same thing.

**Comment by gaborcsardi** [comment]
`skip_if_not_installed()` might be common, but that does not mean it is good practice. Either you want to run the tests, or you don't. "Run the tests, but skip the ones that you cannot run" does not make sense. The CRAN rule of conditionally skipping tests when suggested packages are not available does not make any sense to me. Then just don't run the tests.

asciicast is only used for one test now, but it'll be used for more in the future.

AFAIK there is no reason why you could not install asciicast, it works on all systems we support. What is the environment that you cannot install it in?

**Comment by MichaelChirico** [comment]
> Either you want to run the tests, or you don't. "Run the tests, but skip the ones that you cannot run" does not make sense

I still maintain `skip_if_not_installed()` is the correct choice in the large majority of cases, but for truly required packages, I would add `library(asciicast)` or `loadNamespace("asciicast")` to `testthat.R` to make perfectly clear: this test suite is written with the assumption you have `asciicast` installed.

> What is the environment that you cannot install it in?

Specifically, the Google monorepo. Any new package has to be forked individually. It's safe to assume this will take at least an hour (despite lots of automation) and 2 more days after that for reviewer bandwidth. All the more so (linear scaling) when the package introduces new dependencies also not yet present in the monorepo:

https://opensource.google/documentation/reference/thirdparty/new

I therefore avoid doing so for peripheral packages without broad benefit (e.g. only needed for unit tests).

Another environment with a similar problem that I've worked in is air-gapped machines (e.g. for researchers), or tightly-controlled compute clusters which require individual permissions for each incremental package. The package may install easily once it's available, but using it when `install.packages()` is not available can still be onerous.

**Comment by gaborcsardi** [comment]
> Specifically, the Google monorepo.

Is there a way to detect that?

> Another environment with a similar problem that I've worked in is air-gapped machines (e.g. for researchers), or tightly-controlled compute clusters which require individual permissions for each incremental package. The package may install easily once it's available, but using it when install.packages() is not available can still be onerous.

But I would think that you do not need to run test cases in these environments.

**Comment by MichaelChirico** [comment]
> Is there a way to detect that?

We have a `skip_on_google()` for stuff that's really our own fault. This PR was filed with the hope of being more generally useful.

> you do not need to run test cases in these environments.

Not really. It's true you wouldn't use the test suite the same way a package author/repo maintainer would, but they're still useful as example code & for testing the installation is WAI. If my funny environment has a strange compiler setup, or if I've got my installation in a wonky state, running package test suites can help dig out of the hole.

Anyway, it seems this is not needed in this case -- closing.

**Comment by gaborcsardi** [comment]
I don't mind having some way to opt in into skipping tests that need extra packages. So if you have an env var or something else we can rely on, then we can have

```r
if (Sys.getenv("SKIP_TESTS_WITH_UNAVAILABLE_DEPENDENCIES") != "") { 
  skip_if_not_installed("asciicast")
}
```

If the user opts in, I am fine with that. I just don't want to skip tests for everyone if some package is missing.

**Comment by MichaelChirico** [comment]
FWIW, the testthat report includes a tally of all the skip() reasons. I usually watch that for packages I should include. Not sure how common that workflow is -- admittedly we're already in a unique dev environment.

**Comment by gaborcsardi** [comment]
> FWIW, the testthat report includes a tally of all the skip() reasons.

Sure, but you don't look at that for tests on CI, CRAN, etc.

> I usually watch that for packages I should include. 

You mean you call `skip_if_not_installed()` for every package you use in test cases? I think that's quite common.

**Comment by gaborcsardi** [comment]
So do you think that there is an env var in your environment that we can immediately use for skipping tests?

**Comment by gaborcsardi** [comment]
Actually, we can use `_R_CHECK_FORCE_SUGGESTS_` for this.

**Comment by gaborcsardi** [comment]
Do you run `R CMD check` or run the tests directly?

**Pull request closed without merging**
